source:

  type: vertica
  config:
    host_port: '140.236.88.151:5433'
    database: PartPub80DB
    username: "datahub_user"
    password: "datahub_22"
    include_tables: true
    include_views: true
    include_projections: false
    include_oauth: false
    include_models: false
    include_view_lineage: false
    include_projection_lineage: false
    profiling:  
      enabled: false
    stateful_ingestion: 
      enabled: false



sink:
 # sink configs
 type: 'datahub-rest'



 config:
     server: 'http://localhost:8080'