name: Check Datahub Jars

on:
  push:
    branches:
      - master
    paths-ignore:
      - "docker/**"
      - "docs/**"
      - "**.md"
  pull_request:
    branches:
      - master
    paths-ignore:
      - "docker/**"
      - "docs/**"
      - "**.md"
  release:
    types: [published, edited]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check_jars:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 11
      - uses: actions/setup-python@v4
        with:
          python-version: "3.7"
      - name: check datahub-client jar
        run: |
          ./gradlew :metadata-integration:java:datahub-client:build
          ./gradlew :metadata-integration:java:datahub-client:javadoc
      - name: check spark-lineage jar
        run: |
          ./gradlew :metadata-integration:java:spark-lineage:build
          ./gradlew :metadata-integration:java:spark-lineage:javadoc
      - name: check datahub-protobuf jar
        run: |
          ./gradlew :metadata-integration:java:datahub-protobuf:build
          ./gradlew :metadata-integration:java:datahub-protobuf:javadoc
