name: ingestion base
on:
  release:
    types: [published, edited]
  push:
    branches:
      - master
    paths:
      - "docker/datahub-ingestion/**"
      - "gradle*"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-base:
    name: Build and Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.ACRYL_DOCKER_USERNAME }}
          password: ${{ secrets.ACRYL_DOCKER_PASSWORD }}
      - name: Build and Push image
        uses: docker/build-push-action@v3
        with:
          context: ./docker/datahub-ingestion
          file: ./docker/datahub-ingestion/base.Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: acryldata/datahub-ingestion-base:latest
          push: true
