name: metadata-io
on:
  push:
    branches:
      - master
    paths:
      - "**/*.gradle"
      - "li-utils/**"
      - "metadata-models/**"
      - "metadata-io/**"
  pull_request:
    branches:
      - master
    paths:
      - "**/*.gradle"
      - "li-utils/**"
      - "metadata-models/**"
      - "metadata-io/**"
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 11
      - uses: actions/setup-python@v4
        with:
          python-version: "3.7"
      - name: Gradle build (and test)
        # there is some race condition in gradle build, which makes gradle never terminate in ~30% of the runs
        # running build first without datahub-web-react:yarnBuild and then with it is 100% stable
        # datahub-frontend:unzipAssets depends on datahub-web-react:yarnBuild but gradle does not know about it
        run: |
          ./gradlew :metadata-io:test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Test Results (metadata-io)
          path: |
            **/build/reports/tests/test/**
            **/build/test-results/test/**
            **/junit.*.xml
      - name: Ensure codegen is updated
        uses: ./.github/actions/ensure-codegen-updated

  event-file:
    runs-on: ubuntu-latest
    steps:
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: Event File
          path: ${{ github.event_path }}
